name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Linter Step
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Lint
      run: |
        ./gradlew lint

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: lint.html
        path: app/build/reports/lint-results.html

  unit-test:
    name: Unit Tests
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Tests
      run: |
        ./gradlew test

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: unit_test_report
        path: app/build/reports/tests/testDebugUnitTest/

  instrumentation_test:
    name: Instrumentation Tests
    needs: [unit-test]
    runs-on: macos-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Espresso Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck

    - name: Upload Instrumentation Test Report
      uses: actions/upload-artifact@v4
      with:
        name: instrumentation_test_report
        path: app/build/reports/androidTests/connected/
        emulator-build: 7425822

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    # - name: Build with Gradle
    #   run: ./gradlew build
